[package]
name = "site"
version = "0.1.0"
edition = "2024"

[dependencies]
minijinja = "2.18.0"
pulldown-cmark = "0.13.3"
pulldown-cmark-escape = "0.11.0"
pikchr = "0.1.4"
jiff = { version = "0.2.35", default-features = false, features = [
    "alloc",
    "std",
] }
syn = { version = "3.0.3", features = ["full"] }
quote = "1.0.47"
proc-macro2 = { version = "1.0.107", features = ["span-locations"] }
